### ISSUE TITLE
You skipped an exercise

### ISSUE THREAD

**Issue by vlbrown** [wblakecannon/DataCamp#28]
Exercise 7 should be "Using .nunique() to rank by distinct sports".  All exercises following should have their number bumped by 1.

'''
Using .nunique() to rank by distinct sports

You may want to know which countries won medals in the most distinct sports. The .nunique() method is the principal aggregation here. Given a categorical Series S, S.nunique() returns the number of distinct categories.

Instructions
100 XP
Group medals by 'NOC'.
Compute the number of distinct sports in which each country won medals. To do this, select the 'Sport' column from country_grouped and apply .nunique().
Sort Nsports in descending order with .sort_values() and ascending=False.
Print the first 15 rows of Nsports. This has been done for you, so hit 'Submit Answer' to see the result.
'''

```
# Group medals by 'NOC'
country_grouped = medals.groupby('NOC')

# Compute the number of distinct sports in which each country won medals
Nsports = country_grouped['Sport'].nunique()

# Sort the values of Nsports in descending order
Nsports = Nsports.sort_values(ascending=False)

# Print the top 15 rows of Nsports
print(Nsports.head(15))

```

**Comment by wblakecannon** [comment]
You're free to make a pull request and fix it. I'm not fixing it.
